# Generated by Django 4.0.3 on 2022-08-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('subadmin', 'subadmin'), ('user', 'user')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='super_adminaccount',
            name='Role',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('subadmin', 'subadmin'), ('user', 'user')], default='subadmin', max_length=10),
        ),
    ]
